version: "3.9"
services:
  db:
    image: "rendrum/tidpp:latest"
    
  web:
    build: .
    ports:
      - "8000:8000"
      
  redis:
    image: "redis:alpine"
    
    env_file:
    - ".env"
    
    